export const BASE_URL =  'https://cerulean-marlin-wig.cyclic.app/'
export const FETCH_ALL_ACTIVITIES = 'FETCH_ALL_ACTIVITIES'
export const FETCH_SINGLE_ACTIVITIES = 'FETCH_SINGLE_ACTIVITIES'
export const UPDATE_CALL = "UPDATE_CALL"
export const UPDATE_ALL_CALLS='UPDATE_ALL_CALLS'
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const FETCH_MULTIPLE_ACTIVITIES = 'FETCH_MULTIPLE_ACTIVITIES';